site_name: Hell Let Loose Wiki
use_directory_urls: false
repo_url: https://github.com/hllgame/hllwiki

plugins:
  - glightbox
  - search

theme:
  name: material
  custom_dir: overrides
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: deep orange
  logo: assets/logo.jpeg
  favicon: assets/logo.jpeg
  features:
    - navigation.top
    - toc.integrate